FILENAME REFFILE '/home/mwolfe0/train.csv';

PROC IMPORT DATAFILE=REFFILE DBMS=CSV OUT=HOMES;
	GETNAMES=YES;
RUN;

PROC UNIVARIATE DATA=HOMES;
	VAR GrLIvArea SalePrice;
RUN;

PROC SGPLOT DATA=HOMES;
	SCATTER X=GrLIvArea Y=SalePrice;
	REG X=GrLIvArea Y=SalePrice;
RUN;

PROC REG DATA=HOMES;
	MODEL SalePrice=GrLIvArea;
	RUN;

PROC GLM DATA=HOMES;
	CLASS=Neighborhood;
	MODEL SalePrice=GrLIvArea;
	RUN;